# Generated by Django 4.2.7 on 2025-04-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowstatement',
            old_name='free_cash_flow',
            new_name='free_cashflow',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='cash_and_cash_equivalents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='long_term_debt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='short_term_debt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_shareholder_equity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='common_shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
