# Generated by Django 4.2.7 on 2025-04-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='total_assets',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
