# Generated by Django 4.2.7 on 2025-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_balancesheet_total_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='cash_and_cash_equivalents',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='common_stock_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='net_tangible_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_capitalization',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_equity_gross_minority_interest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_liabilities_net_minority_interest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='working_capital',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
