# Generated by Django 4.2.7 on 2025-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_balancesheet_cash_and_cash_equivalents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflowstatement',
            old_name='free_cashflow',
            new_name='beginning_cash_position',
        ),
        migrations.RenameField(
            model_name='cashflowstatement',
            old_name='operating_cashflow',
            new_name='effect_of_exchange_rate_changes',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='basic_eps',
            new_name='ebit',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='cost_of_revenue',
            new_name='ebitda',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='gross_profit',
            new_name='net_income_from_continuing_operation_net_minority_interest',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_income',
            new_name='normalized_ebitda',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='operating_expense',
            new_name='reconciled_cost_of_revenue',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='total_revenue',
            new_name='reconciled_depreciation',
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='capital_expenditure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='end_cash_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='free_cash_flow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='income_tax_paid_supplemental_data',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='interest_paid_supplemental_data',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='issuance_of_capital_stock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='issuance_of_debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflowstatement',
            name='repayment_of_debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='tax_effect_of_unusual_items',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='tax_rate_for_calcs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='total_unusual_items',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='total_unusual_items_excluding_goodwill',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
