# Generated by Django 4.2.7 on 2025-04-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_rename_free_cashflow_cashflowstatement_beginning_cash_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomestatement',
            old_name='net_income_from_continuing_operation_net_minority_interest',
            new_name='basic_eps',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='normalized_ebitda',
            new_name='cost_of_revenue',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='reconciled_cost_of_revenue',
            new_name='gross_profit',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='reconciled_depreciation',
            new_name='net_income',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='tax_effect_of_unusual_items',
            new_name='operating_expense',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='tax_rate_for_calcs',
            new_name='operating_income',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='total_unusual_items',
            new_name='total_revenue',
        ),
        migrations.AlterUniqueTogether(
            name='incomestatement',
            unique_together={('company', 'fiscal_date_ending')},
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='total_unusual_items_excluding_goodwill',
        ),
    ]
